### ISSUE TITLE
slow?

### ISSUE THREAD

**Issue by ilor2** [smallmuou/wavutils#1]
Thanks for the library!
is it normal that it's pretty slow?

**Comment by yisonPylkita** [comment]
My few cents here.
To convert a *1.2MB* wav file to PCM `wav2pcm` needed *~2.4s*.
Most of the time (*2.2s*) was spent here

```bash
wav2pcm() {
    dd if=$1 of=$2 bs=1 skip=44 > /dev/null 2>&1
}
```

Main contributor here is a parameter `bs=1`. Without him function above takes only *6ms*. This is a *400x* speed-up. So `wav2pcm` can definitely be improved here

**Comment by smallmuou** [comment]
thank for feedback, the tool is based on bash script, It's not very efficient.
